apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-member-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gym-member-app
  template:
    metadata:
      labels:
        app: gym-member-app
    spec:
      containers:
      - name: gym-member-container
        image: saurabhdalvi2424/gym-member-app:latest
        ports:
        - containerPort: 80
