apiVersion: v1
kind: Service
metadata:
  name: gym-member-service
spec:
  type: LoadBalancer  # Use NodePort if testing locally
  selector:
    app: gym-member-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
